### ISSUE TITLE
It is not calling onSuccessful method.

### ISSUE THREAD

**Issue by MuhammadSaqib13** [ErrorxCode/PhoneVerification-API#1]
![image](https://user-images.githubusercontent.com/61687639/217556545-73169a32-7426-44ff-81a9-76576d5c44f8.png)

In this method, there should be calling OnSuccesful(verificationCode).

**Comment by ErrorxCode** [comment]
The callbacks are not called directly. They are called in the `onRecieve()` method of the **SMSReceiver** class. There, some checks are performed before triggering the `onSuccess()` method.

See this line,
```
        context.registerReceiver(new SmsReceiver(),new IntentFilter("SMS_SENT"));
```
and this cause the trigger of callbacks.

**Comment by MuhammadSaqib13** [comment]
I am not getting OTP code through mobile

**Comment by ErrorxCode** [comment]
You might not have a **subscription** to send sms on that particular sim. Try manually sending a _test SMS_ from that sim

**Comment by MuhammadSaqib13** [comment]
OK I will then inform you
